// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xggqnjfxqvqdvlulhlro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnZ3FuamZ4cXZxZHZsdWxobHJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MjE4OTMsImV4cCI6MjA2ODM5Nzg5M30.hYv4zFzA5IYpTwgf12xem0G39I1mr4si0K7vP3q9lyI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});